### ISSUE TITLE
replace esx_context?

### ISSUE THREAD

**Issue by cracktvx** [MauroNr1/esx_identity#1]
hey i love this ! can you maybe replace esx_context with ox_lib too ? thanks in advance

**Comment by MauroNr1** [comment]
Hey, the problem is ox_lib does not allow you to choose menu position so it would look pretty out of place. This is also a seperate resource, esx_multicharacter.

I'm glad you are happy with the resource, but i will upload a new version with some cleaner code. as it is pretty messy atm.
