### ISSUE TITLE
SCRIPT ERROR @esx_identity/client/main.lua:58: attempt to call a nil value (gloval 'setGuiState')

### ISSUE THREAD

**Issue by newbialywhodis** [MauroNr1/esx_identity#2]
after creating a new character we get this error, it seems that it does not affect anything - but yet the very fact that it is displayed. Is it something serious?

**Comment by MauroNr1** [comment]
I'm updating soon with a new version that will fix this, and also clean up some code. But no, this is nothing serious. It's because the nui is not present, this is not an issue in our case as we do not use NUI but use ox_lib.

**Comment by newbialywhodis** [comment]
ah, okay! Thanks for your awesome work btw!

Are you maybe planning to make esx_skin under ox_lib? that would be great

**Comment by MauroNr1** [comment]
No, that is not planned. However, I do suggest using [fivem-appearance](https://github.com/wasabirobby/fivem-appearance) instead. It's what I run on my own server.

**Comment by MauroNr1** [comment]
> after creating a new character we get this error, it seems that it does not affect anything - but yet the very fact that it is displayed. Is it something serious?

Btw, to fix this for now you can simply delete [this line](https://github.com/MauroNr1/esx_identity/blob/f3f88d7c2af7af2ae16dcef7db3fe54bff43c048/client/main.lua#L52).

**Comment by newbialywhodis** [comment]
> No, that is not planned. However, I do suggest using [fivem-appearance](https://github.com/wasabirobby/fivem-appearance) instead. It's what I run on my own server.

Naah, fivem apperance is soo ugly, it would be in my opinion much better with ox_lib list menu

**Comment by MauroNr1** [comment]
> > No, that is not planned. However, I do suggest using [fivem-appearance](https://github.com/wasabirobby/fivem-appearance) instead. It's what I run on my own server.
> 
> Naah, fivem apperance is soo ugly, it would be in my opinion much better with ox_lib list menu

Well, this does not exist, atleast not that I know off. It's also currently not on my list of resources to convert to ox_lib. So no, for now I won't be doing that.

**Comment by MauroNr1** [comment]
Fixed. https://github.com/MauroNr1/esx_identity/releases/tag/v1
